@startuml Izmena prevoda
|Prevodilac|
|Sistem|
start
:Prikazuje listu prevoda sa 
odgovarajućim ključevima;
|Prevodilac|
:Klikne na željeni ključ za koji 
želi da unese ili izmeni prevod;
|Sistem|
:Vraća polja za unos prevoda;
|Prevodilac|
:Unosi ili menja prevod;
:Prevod se automatski šalje na čuvanje 
u trenutku kada tekstualno polje izgubi fokus;
|Sistem|
:Čuva izmenjeni prevod;
stop
@enduml