@startuml Izvoz prevoda
|Prevodilac|
|Sistem|
start
:Prikazuje opcije za uvoz i izvoz prevoda;
|Prevodilac|
:Bira akciju za izvoz prevoda;
|Sistem|
:Prikazuje modal sa formom za unos 
naslova i opisa zahteva za promenu;
|Prevodilac|
:Unosi naslov i opis u tekstualna polja;
:Klikne na dugme OK;
|Sistem|
:Pokreće akciju izvoza projekta;
|GitHub Aplikacija|
:Kreiranje zahteva za promenu sa 
izmenjenim fajlovima;
stop
@enduml
