@startuml Kreiranje projekta
|Prevodilac|
|Sistem|
start
:Prikazuje opciju za kreiranje novog projekta;
|Prevodilac|
:Bira akciju za kreiranje novog projekta;
|Sistem|
:Prikazuje formu za unos podataka o projektu;
|Prevodilac|
:Unosi podatke o projektu;
:Klikne na dugme za kreiranje projekta;
|Sistem|
:Čuva projekat;
:Korisniku vraća stranicu sa podacima o projektu;
stop
@enduml
