@startuml Prijava korisnika
autonumber

group "Prijava korisnika"
    actor Korisnik as user
    participant "Veb aplikacija" as browser
    participant Gateway as gw
    participant "GitHub IdP" as gh


    user -> browser : Klik na dugme za prijavu
    activate browser 
    browser -> gw : Zahtev za prijavu
    activate gw
    gw -> browser : URI ka IDP stranici za prijavu
    deactivate gw
    browser -> user : Preusmeravanje na \nstranicu za prijavu (IDP)
    deactivate browser


    user -> gh : Zahtev za dobijanje \nstranice za prijavu (IDP)
    activate gh
    gh -> user : Stranica za prijavu
    deactivate gh

    user -> gh : Unos kredencijala
    activate gh
    gh -> user : Kod za pristup \n(Uspešno prijavljivanje)
    deactivate gh


    user -> gw : Kod za pristup
    activate gw
    gw -> gh : Kod za pristup
    activate gh
    gh -> gw : Podaci o korisniku
    deactivate gh
    gw -> gw : Generisanje JWT tokena
    gw -> user : JWT token
    deactivate gw
end

group "Zahtev za zaštićenim resursom"
    user -> browser: Zahtev za zaštićenom stranom \n(sa JWT tokenom)
    activate browser
    note over browser: Čuva JWT token \nza buduću komunikaciju

    browser -> gw: Zahtev za zaštićenim resursom \n(JWT token)
    activate gw
    gw -> browser: Zaštićeni resurs
    deactivate gw
    browser -> user : Prikaz zaštićene stranice
    deactivate browser
end
@enduml
