version: '3'

volumes:
  postgres_interpres_data:
    driver: local

services:
  db:
    image: postgres
    volumes:
      - postgres_interpres_data:/var/lib/postgresql/data
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres


  reverse-proxy:
    container_name: reverse-proxy
    build:
      context: ./reverse-proxy
      dockerfile: ./Dockerfile
    image: interpres/reverse-proxy
    ports:
      - 3626:3626


  api-gateway:
    container_name: api-gateway
    build:
      context: server/api-gateway
      dockerfile: ./Dockerfile
    image: interpres/api-gateway
    ports:
      - 8080:8080
    environment:
      JWT_SECRET: ${JWT_SECRET}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      BASE_URL: ${BASE_URL}
      USER_MANAGEMENT_SERVICE_HOST: ${USER_MANAGEMENT_SERVICE_HOST}
      USER_MANAGEMENT_SERVICE_PORT: ${USER_MANAGEMENT_SERVICE_PORT}
      CORE_SERVICE_HOST: ${CORE_SERVICE_HOST}
      CORE_SERVICE_PORT: ${CORE_SERVICE_PORT}
      INTEGRATION_SERVICE_HOST: ${INTEGRATION_SERVICE_HOST}
      INTEGRATION_SERVICE_PORT: ${INTEGRATION_SERVICE_PORT}


  client:
    container_name: client
    build:
      context: client
      dockerfile: ./Dockerfile
    image: interpres/client
    ports:
      - 3000:80


  core:
    container_name: core
    build:
      context: server/core
      dockerfile: ./Dockerfile
    image: interpres/core
    ports:
      - 8091:8091
    depends_on:
      - db
    environment:
      CORE_SERVICE_PORT: ${CORE_SERVICE_PORT}
      CORE_SERVICE_DB_HOST: ${CORE_SERVICE_DB_HOST}
      CORE_SERVICE_DB_PORT: ${CORE_SERVICE_DB_PORT}
      CORE_SERVICE_DB_USERNAME: ${CORE_SERVICE_DB_USERNAME}
      CORE_SERVICE_DB_PASSWORD: ${DB_PASSWORD}
      CORE_SERVICE_DB_DATABASE: ${CORE_SERVICE_DB_DATABASE}


  integration:
    container_name: integration
    build:
      context: server/integration
      dockerfile: ./Dockerfile
    image: interpres/integration
    ports:
    - 8092:8092
    environment:
      INTEGRATION_SERVICE_PORT: ${INTEGRATION_SERVICE_PORT}
      GITHUB_APP_ID: ${GITHUB_APP_ID}
      GITHUB_APP_PRIVATE_KEY: ${GITHUB_APP_PRIVATE_KEY}


  user-management:
    container_name: user-management
    build:
      context: server/user-management
      dockerfile: ./Dockerfile
    image: interpres/user-management
    ports:
      - 8085:8085
    depends_on:
      - db
    environment:
      USER_MANAGEMENT_DB_HOST: ${USER_MANAGEMENT_DB_HOST}
      USER_MANAGEMENT_DB_PORT: ${USER_MANAGEMENT_DB_PORT}
      USER_MANAGEMENT_DB_USERNAME: ${USER_MANAGEMENT_DB_USERNAME}
      USER_MANAGEMENT_DB_PASSWORD: ${DB_PASSWORD}
      USER_MANAGEMENT_DB_DATABASE: ${USER_MANAGEMENT_DB_DATABASE}
      USER_MANAGEMENT_SERVICE_PORT: ${USER_MANAGEMENT_SERVICE_PORT}
