version: '3'

volumes:
  postgres_interpres_data:
    driver: local

services:
  db:
    image: postgres
    volumes:
      - postgres_interpres_data:/var/lib/postgresql/data
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres

  reverse-proxy:
    container_name: reverse-proxy
    build:
      context: ./reverse-proxy
      dockerfile: ./Dockerfile
    image: enco164/reverse-proxy:0.0.1
    ports:
      - 3626:3626

  core-service:
    container_name: core-service
    build:
      context: server/core
      dockerfile: ./Dockerfile
    image: enco164/interpres/translations-service
    ports:
      - ${CORE_SERVICE_PORT}:${CORE_SERVICE_PORT}
    depends_on:
      - db
    environment:
      CORE_SERVICE_DB_HOST: ${CORE_SERVICE_DB_HOST}
      CORE_SERVICE_DB_PORT: ${CORE_SERVICE_DB_PORT}
      CORE_SERVICE_DB_USERNAME: ${CORE_SERVICE_DB_USERNAME}
      CORE_SERVICE_DB_PASSWORD: ${CORE_SERVICE_DB_PASSWORD}
      CORE_SERVICE_DB_DATABASE: ${CORE_SERVICE_DB_DATABASE}

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image: enco164/interpres/client
    ports:
      - 3000:80

  user-management:
    container_name: user-management
    build:
      context: server/user-management
      dockerfile: ./Dockerfile
    ports:
    - 8085:8085
