version: '3'

volumes:
  postgres_interpres_data:
    driver: local

services:
  db:
    image: postgres
    volumes:
      - postgres_interpres_data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: translation
