apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: nginx-ingress
  name: nginx-ingress-controller
data:
  hsts: "true"
  hsts-include-subdomains: "true"
  hsts-max-age: "31536000"
  log-format-escape-json: "true"
  log-format-upstream: '{"message": "$request $status", "status": "$status", "requestTime": "$request_time", "requestLength": "$request_length", "responseLength": "$upstream_response_length", "nodeIp" : "$upstream_addr", "referer": "$http_referer", "userAgent": "$http_user_agent", "remoteIp": "$remote_addr", "service": "$proxy_upstream_name"}'
  proxy-buffer-size: 128k
